(GH-2230) Print Puppetfile diff when using 'module add'
puppetlabs/bolt pull request #2253
Opened 2020-10-09 22:54 UTC by beechtom

This adds a new message to the outputter that describes changes made to
a Puppetfile when using the `bolt module add` / `Add-BoltModule`
command. The message will display which modules have been added,
removed, upgraded, and downgraded. Upgraded and downgraded modules will
have their old version and new version displayed, while added and
removed modules display the version of the module that was added or
removed.

!feature

* **Print changes made to Puppetfile when adding modules**
  ([#2230](https://github.com/puppetlabs/bolt/issues/2230))

  The `bolt module add` command and `Add-BoltModule` cmdlet now display
  a message describing changes made to the Puppetfile, including modules
  that have been added, removed, upgraded, or downgraded.

2020-10-09 23:02 UTC, beechtom commented on lib/bolt/outputter/json.rb
> +      def print_action_step(step)
🚲 🏠 ?

2020-10-10 06:00 UTC, puppetcla commented
CLA signed by all contributors.

2020-10-15 18:42 UTC, nicklewis requested changes

2020-10-15 19:03 UTC, beechtom commented on lib/bolt/module_installer.rb
> +      updated = updated.modules.each_with_object({}) do |mod, acc|
Ah, ya. I had just assumed `new` was a reserved word without actually checking.

2020-10-16 21:49 UTC, merged