(GH-2454) Remove redundant config validation
puppetlabs/bolt pull request #2476
Opened 2020-12-14 22:13 UTC by beechtom

This removes some redundant validation for the `Bolt::Config` class that
is handled by the validator.

!no-release-note

2020-12-14 22:57 UTC, lucywyman requested changes
We also need to do this for the transport configurations, inventory, and plugin config. For example we validate that `login-shells` is one of `LOGIN_SHELLS` in `lib/bolt/config/transport/ssh.rb#L114` when we don't need to

2020-12-14 23:08 UTC, beechtom commented
Updated to remove validation for `login-shells`, which was the only manual validation that didn't get pulled out when I first added the validator to those classes.

We can't really pull out any other manual validation in the inventory classes, since the data needs to be validated after plugins are resolved... we can probably validate that data with the validator class after plugins are resolved, but that would require additional work.

I'm not really sure what you mean by plugin config... we don't have schemas for plugins. Again, we can probably update the built-in plugins to use the validator, but that seems outside the scope of this ticket.

2020-12-14 23:53 UTC, lucywyman commented
There's also redundant timeout validation in `lib/bolt/puppetdb/config.rb`, we can remove `lib/bolt/inventory/group.rb#L253`, I think `lib/bolt/inventory/group.rb#L258` is invalid, or at least I'm not sure how to trigger it? I haven't finished going through all the files but that's at least a few.

2020-12-15 00:05 UTC, beechtom commented
lib/bolt/inventory/group.rb#L253 can't be removed currently because the data it checks might come from a plugin reference, which is not checked by the validator.

lib/bolt/inventory/group.rb#L258 ensures the key itself cannot be a plugin reference. I'm not sure exactly sure why we have that test in the first place, though... I'm fine getting rid of it if we consider it an unlikely scenario that we need to test for.

2020-12-15 00:22 UTC, lucywyman commented
Yeah mostly I'm not sure *how* to make the key a plugin reference, since it has to be a hash and `walk_keys` will walk the keys of the `_plugin` hash and not the whole hash (if that makes sense).

I see what you mean about a lot of validation being after plugins are resolved (like the PuppetDB timeout config).

2020-12-15 15:17 UTC, lucywyman approved these changes
GtG once `lib/bolt/inventory/group.rb#L258` is removed!

2020-12-15 17:43 UTC, merged