(maint) Unpin bundler for Bolt, use bundler 2.1.4 for Litmus CI
puppetlabs/bolt pull request #2490
Opened 2020-12-16 22:35 UTC by lucywyman

We have a CI test that verifies that Litmus works with each Bolt PR by
adding a gem declaration to the Gemfile of
[puppetlabs/puppetlabs-package](https://github.com/puppetlabs/puppetlabs-package)
that pulls in the Bolt PR as a gem and runs tests in the module.
Installing gems in the module was hanging in Github Actions when Bundler 2.2.0
was released, due to [this
issue](https://github.com/rubygems/rubygems/issues/4123). We originally
pinned all of Bolt back to bundler < 2.2.0, however now the Jenkins CI
environment has been updated to only include Bundler 2.2.1. In order to
be able to test and build Bolt in Jenkins we need to unpin the bundler
version so we can use 2.2.1, but still use bundler 2.1.4 for the Litmus
test specifically so that it doesn't hang.

!no-release-note

2020-12-16 22:46 UTC, lucywyman commented
We're going to hold off on merging this until after the Bolt-team break that starts on Monday. We'll be back Monday the 4th!

2020-12-18 17:06 UTC, beechtom approved these changes

2021-01-04 17:45 UTC, beechtom requested changes
We can unpin bundler for the litmus smoke tests as well since the bug in bundler was resolved in [2.2.3](https://github.com/rubygems/rubygems/pull/4179).

2021-01-04 18:54 UTC, beechtom approved these changes

2021-01-04 18:54 UTC, merged