(GH-2559) Remove deprecated command-line options
puppetlabs/bolt pull request #2569
Opened 2021-01-21 05:09 UTC by beechtom

This removes support for deprecated command-line options:

- `--boltdir`
- `--configfile`
- `--debug`
- `--description`

This also removes the `Bolt::Config.from_file` factory method, since it
is only used when using the `--configfile` command-line option.

!removal

* **Remove deprecated command-line options**
  ([#2559](https://github.com/puppetlabs/bolt/issues/2559))

  The `--boltdir`, `--configfile`, `--debug`, and `--description`
  command-line options have been removed.

2021-01-21 22:20 UTC, lucywyman requested changes
I think we should also update `resources/bolt_bash_completion.sh`. This also needs to include `--inventoryfile`, and I think should also include `--puppetfile` (which doesn't seem to be in the developer update? It'd be good to add that here too https://puppet.com/docs/bolt/latest/developer_updates.html).

Tests:
- [x] Using any of the commandline options raises an error

2021-01-21 22:29 UTC, beechtom commented
@lucywyman We aren't removing support for either `--inventoryfile` or `--puppetfile`.

2021-01-21 22:41 UTC, lucywyman commented
Sorry, we aren't for `--inventoryfile`, but we are removing `--puppetfile`:
```
lucy ~/githubs/bolt/project (refactor-transport) $ be bolt module install --puppetfile Puppetfile --force
Unknown option 'disable-warnings' at /home/lucy/githubs/bolt/project/bolt-project.yaml.
Command line option '--puppetfile' is deprecated, and will be removed in Bolt 3.0. You can migrate to using the new module management workflow using 'bolt project migrate'.
```

2021-01-22 17:14 UTC, lucywyman commented on resources/bolt_bash_completion.sh
> +	local project_config_opts="--project"
File also needs to have --puppetfile reference removed on line 65.

2021-01-22 17:22 UTC, lucywyman commented on lib/bolt/cli.rb
>                    cli_flag = options[:project] || options[:boltdir]
`options[:boltdir]` can't be set anymore, this can be inlined to the `if` below.

2021-01-22 17:28 UTC, lucywyman approved these changes
Few small comments, looks good!

- [x] Errors when CLI option is used:
  - [x] --configfile
  - [x] --boltdir
  - [x] --description
  - [x] --debug
  - [x] --puppetfile
- [x]  Does not autocomplete
  - [x] --configfile
  - [x] --boltdir
  - [x] --description
  - [x] --debug
  - [x] --puppetfile
- [x] No references in codebase
  - [x] --configfile
  - [x] --boltdir
  - [x] --description
  - [x] --debug - This is still referenced at `spec/fixtures/linuxdev/bolt-kerberos-test.sh`, but I don't think we use that.
  - [x] --puppetfile
- [x] Still respects `--project`
- [x] Does not call `Config.from_file`
- [x] Respects `description` set in a plan

2021-01-22 18:06 UTC, merged