(GH-2552) bundled-ruby transport config now defaults to true
puppetlabs/bolt pull request #2589
Opened 2021-01-28 16:01 UTC by lucywyman

The local transport's `bundled-ruby` configuration option, which
determines whether to use the Ruby bundled with Bolt packages for local
targets, now defaults to 'true' instead of 'false'. The option can still
be configured as before.

!feature

* **Local transport's 'bundled-ruby' option defaults to true**
  The local transport's `bundled-ruby` configuration option, which
  determines whether to use the Ruby bundled with Bolt packages for local
  targets, now defaults to 'true' instead of 'false'. The option can still
  be configured as before.

2021-01-28 21:59 UTC, lucywyman commented
Relies on #2597

2021-01-28 23:37 UTC, beechtom requested changes
I think https://github.com/puppetlabs/bolt/blob/main/lib/bolt/transport/local.rb#L18-L24 needs to be removed.

2021-01-29 13:49 UTC, lucywyman commented
This does have one weird edge case I found, which is that previously we merged in the `localhost` defaults for any target named localhost. In order for `bundled-ruby` to also be able to configure `localhost` (which is still the only target that automatically uses the `local` transport), we need to, well, only apply the defaults if `bundled-ruby` is true. That means that previously `ssh://localhost` would have picked up the `puppet-agent` feature, and it won't anymore. I doubt anyone will run in to that, but it's just good to know and record.

2021-01-29 17:44 UTC, beechtom approved these changes

2021-01-29 17:44 UTC, merged