(maint) Update Puppetfile to include puppet_connect module
puppetlabs/bolt pull request #2645
Opened 2021-02-17 16:21 UTC by McdonaldSeanp

This commit updates the Puppetfile bolt uses during packaging steps to include
the puppet_connect module so that it isn't overwritten by r10k during builds

2021-02-17 16:24 UTC, donoghuc approved these changes

2021-02-17 17:43 UTC, nicklewis commented
Do we also need a corresponding update to the hardcoded list of bundled content used for detecting rubygems installs?

2021-02-17 17:54 UTC, donoghuc commented
I dont think so. https://github.com/puppetlabs/bolt/blob/8e14757f6ea72f09c8bc5f512b8a7d7dbe4cb979/bolt.gemspec#L24-L36 looks like we are covered

2021-02-17 17:56 UTC, nicklewis commented
This is what I was referring to:

https://github.com/puppetlabs/bolt/blob/main/lib/bolt/cli.rb#L902

I think this PR as it stands will cause the warning about gem installs to never trigger.

2021-02-17 17:57 UTC, donoghuc commented
Oh you mean this https://github.com/puppetlabs/bolt/blob/8e14757f6ea72f09c8bc5f512b8a7d7dbe4cb979/lib/bolt/cli.rb#L899-L903

2021-02-17 18:08 UTC, nicklewis requested changes

2021-02-17 18:08 UTC, nicklewis commented on lib/bolt/cli.rb
> +      (Dir.children(Bolt::Config::Modulepath::MODULES_PATH) - %w[aggregate canary puppetdb_fact secure_env_vars puppet_conenct]).empty?
```suggestion
      (Dir.children(Bolt::Config::Modulepath::MODULES_PATH) - %w[aggregate canary puppetdb_fact secure_env_vars puppet_connect]).empty?
```

2021-02-17 18:09 UTC, McdonaldSeanp commented on lib/bolt/cli.rb
> +      (Dir.children(Bolt::Config::Modulepath::MODULES_PATH) - %w[aggregate canary puppetdb_fact secure_env_vars puppet_conenct]).empty?
damnit

2021-02-18 20:29 UTC, beechtom approved these changes

2021-02-18 21:45 UTC, donoghuc approved these changes

2021-02-18 21:45 UTC, merged