2653/merged output
puppetlabs/bolt pull request #2702
Opened 2021-03-10 23:29 UTC by beechtom

2021-03-15 21:00 UTC, lucywyman requested changes
Hm I think at least one test should verify that values to the stdout and stderr streams get merged in `merged_output`.

2021-03-15 21:02 UTC, lucywyman commented
- It logs both stdout and stderr in the same output stream
  - [x] Human outputter on *nix
  - [x] Human outputter on windows
  - [x] Includes `merged_output`, `stdout`, and `stderr` in JSON outputter
- [x] Adds 'merged_output' key to Result object with the merged streams in order
  - [x] Value can be accessed by `$result.value['merged_output']`
- [x] Maintains `stdout` as it's own key on Result objects
- [x] Maintains `stderr` as it's own key on Result objects
- [x] Returns `merged_output` key from BoltSpec `run_command` function
- [x] Returns `merged_output` key from BoltSpec `run_script` function
- [x] It doesn't append extra characters if either stream has no content
- [x] It returns an empty string if neither stream has output
- [x] Works with `--tty` specified

2021-03-15 21:50 UTC, hestonhoffman approved these changes
Docs LGTM. One small thing. I wonder if we can include a cross link to writing_plans.md#returning-results-from-plans in this section (if that's the right place for people to learn about using these results).

2021-03-16 18:45 UTC, lucywyman approved these changes
:worried: This is definitely a big change, I'm honestly nervous about what folks will think. :crossed_fingers: It's well received.

2021-03-16 18:45 UTC, merged