(maint) Address puppetlabs_spec_helper deprecation warning
puppetlabs/bolt pull request #2753
Opened 2021-03-31 00:04 UTC by lucywyman

The `puppetlabs_spec_helper` ruby library we use as part of testing
embedded Bolt modules was raising a deprecation warning that the default
mocking framework was `mocha` but that to silence the warning the tests
themselves should specify which framework was being used. While I'd
honestly love to switch to `rspec` it's a lot of work to do so for
relatively little gain. For now setting the configuration to `mocha` to
silence the warning is easiest.

!no-release-note

2021-03-31 15:32 UTC, beechtom requested changes
`bolt_spec_spec` and the modules in `modules/` also need this config change.

2021-03-31 22:19 UTC, lucywyman commented
Good call, updated

2021-04-01 18:20 UTC, beechtom requested changes
https://github.com/puppetlabs/bolt/blob/main/bolt_spec_spec/spec/functions/with_datatype_spec.rb#L3

RSpec needs to be configured before `puppetlabs_spec_helper/module_spec_helper` is loaded, so this line should be moved after `require 'spec_helper'` or to the end of `spec_helper.rb` similar to the other modules.

2021-04-02 19:56 UTC, beechtom approved these changes

2021-04-02 19:56 UTC, merged