(bug) Provide project for BoltSpec::Run::Runner#pal
puppetlabs/bolt pull request #2858
Opened 2021-05-28 01:22 UTC by jpartlow

Ran into a case where using BoltSpec::Run.run_plan with a plan
containing a download_file() call would fail here:

https://github.com/puppetlabs/bolt/blob/3.9.0/bolt-modules/boltlib/lib/puppet/functions/download_file.rb#L99

because Puppet.lookup(:bolt_project) would otherwise be null at this
point.

Providing the config.project to the Bolt::PAL instance created by
BoltSpec::Run::Runner#pal fixes this.

2021-05-28 01:24 UTC, jpartlow commented
Not sure that this patch is in the right spot, or that the spec would be wanted, but I think it at least illustrates what I bumped into.

2021-06-01 16:08 UTC, beechtom requested changes
Definitely the right place for this fix! Thanks for catching this.
When you have a chance, can you add a release note to the end of your commit? It should look like this:

```
!bug

* **Descriptive title of changes**
  ([#2858](https://github.com/puppetlabs/bolt/pull/2858))

  Descriptive summary of changes.
```

2021-06-01 16:16 UTC, jpartlow commented
Yep, I'll add that in.

2021-06-01 16:49 UTC, beechtom approved these changes

2021-06-01 16:49 UTC, merged

2021-06-01 16:50 UTC, jpartlow commented
Thanks! o/