(maint) Remove unsupported platforms
puppetlabs/bolt pull request #2948
Opened 2021-07-22 15:44 UTC by lucywyman

The release engineering team is removing vanagon support for Fedora 30,
Fedora 31, and OSX 10.14, in addition to removing support for the Puppet
Agent. This means that Bolt can no longer build packages for these
platforms, so is removing them.

!deprecation

* **Remove support for Fedora 30, Fedora 31, and OSX 10.14**

2021-07-22 21:32 UTC, beechtom requested changes
Can you update the release note to say "macOS 10.14" instead of "OSX 10.14"?

2021-07-23 15:35 UTC, beechtom approved these changes

2021-07-23 15:36 UTC, beechtom requested changes
The release note tag for this should be `!removal`

2021-07-23 16:37 UTC, hestonhoffman approved these changes

2021-07-23 21:57 UTC, beechtom approved these changes

2021-07-23 21:58 UTC, merged