2910/require relative
puppetlabs/bolt pull request #2960
Opened 2021-07-29 21:36 UTC by artlawson

2021-08-03 19:49 UTC, beechtom requested changes
The paths in the `bolt_spec` and `bolt_server` files are incorrect. I think we should avoid changing these anyways and focus on just `bolt` files (unless @lucywyman has other thoughts?).

2021-08-06 17:46 UTC, beechtom requested changes
This needs to be rebased off `main`.

2021-08-06 18:12 UTC, donoghuc commented
I would love it if somebody builds this into a PE install and runs the orch tests against it. Given the issues we saw with puppet moving to relative_require i want to double check there wont be strange code loading issues.

2021-09-01 18:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/bolt?pullRequest=2960) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/bolt?pullRequest=2960) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/bolt?pullRequest=2960) it.</sub>

2021-09-02 18:00 UTC, lucywyman commented
Sweet, finally got a green run for this in the Orchestrator!

2021-09-02 20:52 UTC, beechtom requested changes
1. This also needs to update paths in `lib/bolt/application.rb`.
2. The commit message has two release note tags. We should probably remove `!feature`.

2021-09-02 20:52 UTC, beechtom commented on lib/bolt/secret.rb
> +# frozen_string_literal: true
Need to delete this file.

2021-09-03 16:59 UTC, beechtom approved these changes

2021-09-03 16:59 UTC, merged