Permit aliases in yaml files
puppetlabs/bolt pull request #3021
Opened 2021-09-13 18:04 UTC by reidmv

Ruby's YAML::safe_load method is used to load yaml files. By default,
::safe_load will error on yaml files that contain references and
aliases.

This commit passes `aliases: true` to ::safe_load so that users can use
yaml files which contain aliases.

This is specifically useful when hand-writing complex inventory files
using plugins, to avoid huge amounts of copy-pasta of plugin boilerplate
content in similar targets/groups.

2021-09-13 18:05 UTC, reidmv commented
This is the kind of inventory file I wanted to use, when I ran into the problem.

```yaml
---
config:
  transport: ssh
  ssh:
    host-key-check: false
    run-as: root
    user: bolt-admin
groups:
  - name: peadm_nodes
    groups:
      - name: pe-cluster-1
        targets:
          - &tf
            _plugin: terraform
            dir: pe-cluster-1/.terraform/google_pe_arch
            resource_type: google_compute_instance.server
            target_mapping:
              name: metadata.internalDNS
              uri: network_interface.0.access_config.0.nat_ip
          - << : *tf
            dir: pe-cluster-1/.terraform/google_pe_arch
            resource_type: google_compute_instance.compiler
          - << : *tf
            dir: pe-cluster-1/.terraform/google_pe_arch
            resource_type: google_compute_instance.psql
      - name: pe-cluster-2
        targets:
          - << : *tf
            dir: pe-cluster-2/.terraform/google_pe_arch
            resource_type: google_compute_instance.server
          - << : *tf
            dir: pe-cluster-2/.terraform/google_pe_arch
            resource_type: google_compute_instance.compiler
          - << : *tf
            dir: pe-cluster-2/.terraform/google_pe_arch
            resource_type: google_compute_instance.psql
      - name: pe-cluster-3
        targets:
          - << : *tf
            dir: pe-cluster-3/.terraform/google_pe_arch
            resource_type: google_compute_instance.server
          - << : *tf
            dir: pe-cluster-3/.terraform/google_pe_arch
            resource_type: google_compute_instance.compiler
          - << : *tf
            dir: pe-cluster-3/.terraform/google_pe_arch
            resource_type: google_compute_instance.psql
  - name: agent_nodes
    targets:
      - << : *tf
        dir: pe-cluster-1/.terraform/google_pe_arch
        resource_type: google_compute_instance.node
      - << : *tf
        dir: pe-cluster-2/.terraform/google_pe_arch
        resource_type: google_compute_instance.node
      - << : *tf
        dir: pe-cluster-3/.terraform/google_pe_arch
        resource_type: google_compute_instance.node
```

2021-09-13 18:16 UTC, nicklewis commented
Would it work to put that shared plugin config in `bolt-project.yaml` instead of repeating it (whether via aliases or not) in the inventory file?

2021-09-13 18:18 UTC, lucywyman commented
There are several reasons we don't want to support aliases in Bolt:
* Most important, supporting YAML aliases in other tools that consume Bolt configuration and inventory files will be a heavy lift
* With pluggable config files, aliasing could get complicated and hard to debug very quickly
* This behavior is already basically supported with the YAML plugin
* Psych has this disabled by default
* Anchors would be lost during `project migrate` and any other operations that modify YAML files

2021-09-13 19:19 UTC, reidmv commented
> * **Supporting YAML aliases in other tools that consume Bolt configuration and inventory files will be a heavy lift.**

Curious, which tools? As a user, I am very surprised when _any_ tools don't support anchors/aliases, since it is [part of the YAML spec](https://yaml.org/spec/1.2.1/#id2785586).

> * **Psych has this disabled by default.**

(Reordered this point, as it addresses an implicit question from the preceding.)

Wait, but why is it disabled in Psych then, if it's part of the spec?

The answer requires a clarification. _`Psych::safe_load`_ is what disables anchors by default. `::safe_load` disables some Psych features, and some spec features, in order to guard against specific possible attack vectors. `Psych::load` doesn't disable aliases by default.

Some brief research into the reasoning for `::safe_load` [suggests that](https://makandracards.com/makandra/465149-ruby-the-yaml-safe_load-method-hides-some-pitfalls#note-section-a-note):

> Parsing aliases allows "YAML bombs" that also constitute a DOS attack. You have to choose if this is acceptable risk for your use case.

This is the potential attack `::safe_load` protects against by disabling the spec feature. For Bolt's use case, I don't believe this is a serious concern. We aren't accepting YAML inputs over an open wire, and if someone has access to an input YAML file, I'm not sure we're worried about a DDOS. I believe the user utility of writing standard YAML to spec and having it work correctly outweighs this concern.

**Note:** IMO, whether or not we feel we need to guard against this attack should be the deciding factor here. The rest of the points don't give us a strong enough excuse not to adhere to the YAML spec.

Remaining points responded to below the line.

-----

> * **Anchors would be lost during project migrate and any other operations that modify YAML files**

This is expected and understood by users of anchors. The yaml spec makes no promises about preserving aliases; in fact, [it kinda seems to dictate that they be discarded](https://yaml.org/spec/1.2.1/#representation//) when round-tripping data. In any case, no library that I've encountered has preserved them, and as such this behavior is fully expected. It's a user decision as to whether the benefit is worth the cost.

> * **With pluggable config files, aliasing could get complicated and hard to debug very quickly.**

This point starts to drift into having a position on how users _should_ use our tool. This is absolutely a valid position to take in a style guide, but it shouldn't inform a decision about whether or not to omit a feature of the YAML spec.

By using YAML, we present an industry standard interface to our users. We can (and should) make style recommendations with regard to it, but we shouldn't deviate from the spec without very good reasons. That undermines the user comfort we built by using it in the first place.

> * **This behavior is already basically supported with the YAML plugin.**

That's great! But... a user has to discover that this plugin exists and learn it before it is useful to them. It doesn't enable some users to effortlessly leverage their existing knowledge the way YAML spec features do. I don't want to downplay or undermine the plugin, but I don't think its existence mitigates the main concern I have with not supporting this feature of the YAML spec.

2021-10-04 19:16 UTC, reidmv commented
While I will go on the record as disagreeing with the decision not to support the use of aliases, the highest UX value is clarity. Therefore, I am modifying this PR to instead of supporting aliases, raise a meaningful and clear message when aliases are encountered, so that users encountering this limitation are made aware that it is not bug, but an intentional design decision.

2021-10-04 19:22 UTC, reidmv commented on lib/bolt/util.rb
> +        raise Bolt::FileError.new("Bolt does not support the use of aliases in Yaml files. Alias detected in #{file_name} file at #{path}\n#{e.message}",
Updated. Rolled into an amendment that fixes the linter error.

2021-10-04 19:34 UTC, beechtom requested changes
Can you drop commit 3de5503 ?

2021-10-04 20:10 UTC, reidmv commented
@beechtom if you'd like me to drop the first commit I can, yes. As written, it is there intentionally, and is currently referenced in the latter commit's message. But if the Bolt team prefers not to preserve commit history meaningful to the decision process it's easy to delete. Please confirm which direction you'd like to go.

2021-10-04 20:31 UTC, beechtom commented
@reidmv Yes, please drop the commit.

2021-10-04 21:20 UTC, reidmv commented
@beechtom pushed.

There seem to be spurious test suite failures occurring most times when I push this. Never the same thing twice though; once with a Windows integration suite, and once with a Linux integration thing, none of it apparently related to this change. Any idea what's up with that?

2021-10-04 21:25 UTC, beechtom commented
@reidmv Just a couple flaky tests that we haven't had time to look into.

2021-10-04 21:43 UTC, beechtom approved these changes

2021-10-04 21:43 UTC, merged