Improve inventory target name resolution performance
puppetlabs/bolt pull request #3291
Opened 2024-04-02 16:37 UTC by seanmil

When resolving a large number of targets from a plan the match_wildcard? regex is compiled on the fly possibly hundreds or thousands (for a large inventory) of times per target name resolution.

Switching to File.fnmatch provides a significant speed increase and seems to more accurately reflect the
functionality stated in the Bolt documentation with regards to target matching.

2024-04-02 16:39 UTC, seanmil commented
The documentation for the plan functions get_target and get_targets do not mention anything about wildcard support, but the Bolt documentation at https://www.puppet.com/docs/bolt/latest/running_bolt_commands#specify-targets-using-glob-matching mentions at the bottom that "Extended glob matching is only supported when specifying targets from the command-line interface. Plans do not support extended glob matching." - which seems to imply that basic glob matching should be supported.

2024-04-02 18:57 UTC, donoghuc commented
I'll have to debug the tests (i'll do this in a separate PR). Assuming all the tests pass I think this is a great improvement. i agree with your assessment and interpretation of the intent for matching. Thanks!

2024-04-03 01:01 UTC, seanmil commented
> I'll have to debug the tests (i'll do this in a separate PR). Assuming all the tests pass I think this is a great improvement. i agree with your assessment and interpretation of the intent for matching. Thanks!

I made one more improvement to do an exact-match lookup instead of the slower wildcard if there are no wildcard characters.

In my ~3,300 target string name `get_targets` call it went from around 30s to 7s with the regex-to-fnmatch change and then from 7s to 0.035s with the exact-match logic change.

2024-04-16 22:01 UTC, donoghuc approved these changes

2024-04-16 22:04 UTC, donoghuc commented
Now that I got tests unblocked, you can see a couple cases we will need to address with this work.

2024-04-16 22:05 UTC, donoghuc requested changes
Failing tests:
```
Failures:

  1) Bolt::Target when parsing userinfo strips brackets from ipv6 addresses in a uri
     Failure/Error: raise(WildcardError, target) if targets.empty?

     Bolt::Inventory::Inventory::WildcardError:
       Found 0 targets matching wildcard pattern ssh://[::1]:22
     # ./lib/bolt/inventory/inventory.rb:160:in `resolve_name'
     # ./lib/bolt/inventory/inventory.rb:180:in `block in expand_targets'
     # ./lib/bolt/inventory/inventory.rb:179:in `map'
     # ./lib/bolt/inventory/inventory.rb:179:in `expand_targets'
     # ./lib/bolt/inventory/inventory.rb:99:in `get_targets'
     # ./lib/bolt/inventory/inventory.rb:108:in `get_target'
     # ./spec/unit/target_spec.rb:177:in `block (3 levels) in <top (required)>'

  2) Bolt::Target when parsing userinfo returns set object with feature_set
     Failure/Error: raise(WildcardError, target) if targets.empty?

     Bolt::Inventory::Inventory::WildcardError:
       Found 0 targets matching wildcard pattern ssh://[::1]:22
     # ./lib/bolt/inventory/inventory.rb:160:in `resolve_name'
     # ./lib/bolt/inventory/inventory.rb:180:in `block in expand_targets'
     # ./lib/bolt/inventory/inventory.rb:179:in `map'
     # ./lib/bolt/inventory/inventory.rb:179:in `expand_targets'
     # ./lib/bolt/inventory/inventory.rb:99:in `get_targets'
     # ./lib/bolt/inventory/inventory.rb:108:in `get_target'
     # ./spec/unit/target_spec.rb:192:in `block (3 levels) in <top (required)>'

Finished in 18.04 seconds (files took 1.62 seconds to load)
[153](https://github.com/puppetlabs/bolt/actions/runs/8713085630/job/23900793508?pr=3291#step:7:154)6 examples, 2 failures

Failed examples:

rspec ./spec/unit/target_spec.rb:176 # Bolt::Target when parsing userinfo strips brackets from ipv6 addresses in a uri
rspec ./spec/unit/target_spec.rb:191 # Bolt::Target when parsing userinfo returns set object with feature_set
```

2024-05-20 21:31 UTC, donoghuc commented
triggering a CI run by opening and then closing this PR.

2024-05-20 22:21 UTC, donoghuc commented
Ah, so it looks like this actually exposed a small issue in our tests https://github.com/puppetlabs/bolt/pull/3318 

I think the fact that this now results in raising a `WildcardError` instead of letting `#{target}` through is an improvement. Thanks!

2024-05-20 22:24 UTC, donoghuc approved these changes

2024-05-21 20:22 UTC, mcdonaldseanp approved these changes
@seanmil I just pushed the test fix from Cas to main, if you rebase this on that and we see a green run we'll merge.

2024-05-21 23:43 UTC, seanmil commented
> @seanmil I just pushed the test fix from Cas to main, if you rebase this on that and we see a green run we'll merge.

All green (finally!), thanks!

2024-05-22 22:03 UTC, merged

2024-05-22 22:03 UTC, donoghuc commented
Thank you!